/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AnsiSchema {
  normal: {
    blue: string;
    cyan: string;
    green: string;
    magenta: string;
    red: string;
    yellow: string;
  };
  bright: {
    blue: string;
    cyan: string;
    green: string;
    magenta: string;
    red: string;
    yellow: string;
  };
}
