/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UiSchema {
  shadow: string;
  border: string;
  background: string;
  backgroundAlt: string;
  accent: string;
  accentAlt: string;
  secondaryAccent: string;
  secondaryAccentAlt: string;
  tertiaryAccent: string;
  positive: string;
  negative: string;
  warning: string;
  modified: string;
  lightText: string;
  darkText: string;
}
